export enum ErrorCodes {
  INVALID_JSON = "INVALID_JSON",
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  RAW_BODY_REQUIRED = "RAW_BODY_REQUIRED",
  REJECTION_REASON_REQUIRED = "REJECTION_REASON_REQUIRED",
  MISSING_SIGNATURE = "MISSING_SIGNATURE",
  INVALID_SIGNATURE = "INVALID_SIGNATURE",
  UNAUTHORIZED = "UNAUTHORIZED",
  CONFIG_ERROR = "CONFIG_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

export type ErrorCode = keyof typeof ErrorCodes | string;
